-- Add ipeds_id to cds_documents. This is the join key for the College
-- Scorecard summary table (PRD: docs/research/scorecard-summary-table-v2-plan.md)
-- and the foundation for all cross-dataset joins with federal data (IPEDS,
-- NSLDS, Treasury earnings, etc.) that share UNITID as a primary identifier.
--
-- Sourced from tools/finder/schools.yaml at archive time. Backfill is a
-- one-shot UPDATE per existing school, generated by
-- tools/scorecard/backfill_ipeds_ids.py from schools.yaml.

ALTER TABLE public.cds_documents
  ADD COLUMN ipeds_id text;

COMMENT ON COLUMN public.cds_documents.ipeds_id IS
  'IPEDS Unit ID (UNITID). Six-digit NCES identifier. '
  'Sourced from tools/finder/schools.yaml at archive time. '
  'Foreign key into scorecard_summary and the federal College Scorecard API.';

CREATE INDEX idx_cds_documents_ipeds_id ON public.cds_documents (ipeds_id);

-- Recreate cds_manifest view to expose ipeds_id.
-- Must DROP + CREATE (not CREATE OR REPLACE) because adding a column changes
-- column order, which Postgres disallows for REPLACE.
--
-- FUTURE MIGRATION AUTHORS: After migration 20260420170200 lands,
-- public.cds_scorecard depends on cds_manifest. Any future migration
-- that needs to recreate cds_manifest must drop cds_scorecard first,
-- or use DROP VIEW ... CASCADE followed by recreating both views.
-- The pattern is:
--   DROP VIEW IF EXISTS public.cds_scorecard;
--   DROP VIEW IF EXISTS public.cds_manifest;
--   CREATE VIEW public.cds_manifest AS ...;
--   CREATE VIEW public.cds_scorecard WITH (security_invoker = true) AS ...;
DROP VIEW IF EXISTS public.cds_manifest;

CREATE VIEW public.cds_manifest AS
  SELECT
    d.id                   AS document_id,
    d.school_id,
    d.school_name,
    d.ipeds_id,
    d.sub_institutional,
    d.cds_year,
    d.source_url,
    d.source_format,
    d.participation_status,
    d.discovered_at,
    d.last_verified_at,
    d.removed_at,
    d.extraction_status,
    (
      SELECT a.id
      FROM public.cds_artifacts a
      WHERE a.document_id = d.id AND a.kind = 'canonical'
      ORDER BY a.created_at DESC
      LIMIT 1
    ) AS latest_canonical_artifact_id,
    (
      SELECT a.storage_path
      FROM public.cds_artifacts a
      WHERE a.document_id = d.id AND a.kind = 'source'
      ORDER BY a.created_at DESC
      LIMIT 1
    ) AS source_storage_path,
    d.detected_year,
    COALESCE(d.detected_year, d.cds_year) AS canonical_year,
    d.data_quality_flag
  FROM public.cds_documents d;

GRANT SELECT ON public.cds_manifest TO anon, authenticated;

COMMENT ON VIEW public.cds_manifest IS
  'Convenience view joining cds_documents to their most recent canonical '
  'artifact and archived source file. Query this view when you want '
  '"latest structured data per school" as a single join-free GET. '
  'Prefer canonical_year over cds_year. data_quality_flag surfaces '
  'publisher-side issues. ipeds_id joins to scorecard_summary.';
