#!/usr/bin/env python3
"""Populate cds_documents.ipeds_id for every school that already has rows
in the archive, reading the canonical (school_id → IPEDS) crosswalk from
tools/finder/schools.yaml.

Run once after the 20260420170000_ipeds_id.sql migration has been
applied. New archives written after that migration pick up ipeds_id
automatically via the archive-process / archive-upload edge functions
(see _shared/archive.ts). This script only fixes the pre-existing rows.

Usage:
    # Dry run — print the SQL that would be executed, no DB writes
    python tools/scorecard/backfill_ipeds_ids.py

    # Apply directly via service-role client (requires .env with
    # SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY)
    python tools/scorecard/backfill_ipeds_ids.py --apply

    # Emit SQL only (for psql / Supabase SQL editor)
    python tools/scorecard/backfill_ipeds_ids.py --emit-sql > backfill.sql

The --emit-sql form is the safest path for production: review the diff,
paste into the Supabase SQL editor, run, done.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHOOLS_YAML = REPO_ROOT / "tools" / "finder" / "schools.yaml"

# IPEDS UNITIDs are NCES-issued numeric identifiers, historically 6 digits
# but with some shorter ones in the legacy cohort. We accept 3-8 digits and
# reject anything else — this is the trust boundary for the SQL generator
# and the supabase-py writer below. Both paths MUST refuse to propagate a
# value that fails this check, because the --emit-sql path is pasted into
# an operator's SQL editor with elevated privileges.
IPEDS_RE = re.compile(r"^\d{3,8}$")


def load_crosswalk() -> dict[str, str]:
    """Return {school_id: ipeds_id} for every schools.yaml entry that has
    a well-formed UNITID. Entries without an IPEDS ID (verified-absent or
    manually-added rows), or with a malformed one, are skipped and logged
    to stderr so operators notice schema drift."""
    with SCHOOLS_YAML.open() as f:
        data = yaml.safe_load(f)
    crosswalk: dict[str, str] = {}
    skipped: list[tuple[str, str]] = []
    for entry in data.get("schools", []):
        sid = entry.get("id")
        ipeds = entry.get("ipeds_id")
        if not (sid and ipeds):
            continue
        ipeds_str = str(ipeds)
        if not IPEDS_RE.fullmatch(ipeds_str):
            skipped.append((sid, ipeds_str))
            continue
        crosswalk[sid] = ipeds_str
    if skipped:
        print(
            f"Skipped {len(skipped)} schools with malformed ipeds_id: "
            + ", ".join(f"{s}={v!r}" for s, v in skipped[:5])
            + (" ..." if len(skipped) > 5 else ""),
            file=sys.stderr,
        )
    return crosswalk


def generate_sql(crosswalk: dict[str, str]) -> str:
    """Build a single transaction that fills in ipeds_id for every row
    whose school_id matches the crosswalk and whose ipeds_id is currently
    NULL. We use VALUES + JOIN so the statement is one round-trip and
    ~instant even with thousands of schools."""
    lines = [
        "-- Generated by tools/scorecard/backfill_ipeds_ids.py",
        "-- Populates cds_documents.ipeds_id for existing rows where schools.yaml",
        "-- has a known IPEDS UNITID. Safe to re-run (no-op when ipeds_id is",
        "-- already set).",
        "BEGIN;",
        "",
        "WITH crosswalk(school_id, ipeds_id) AS (",
        "  VALUES",
    ]
    rows = sorted(crosswalk.items())
    for i, (sid, ipeds) in enumerate(rows):
        # Defensive escaping — load_crosswalk already validates that ipeds
        # matches IPEDS_RE (digits only), so it cannot contain quotes. We
        # still pass it through the same '' escape as sid to keep the
        # invariant "every SQL-embedded value is escaped" visible at the
        # point of use, which makes future edits to load_crosswalk safer.
        sid_esc = sid.replace("'", "''")
        ipeds_esc = ipeds.replace("'", "''")
        sep = "," if i < len(rows) - 1 else ""
        lines.append(f"    ('{sid_esc}', '{ipeds_esc}'){sep}")
    lines += [
        ")",
        "UPDATE public.cds_documents d",
        "SET ipeds_id = c.ipeds_id",
        "FROM crosswalk c",
        "WHERE d.school_id = c.school_id",
        "  AND d.ipeds_id IS NULL;",
        "",
        "COMMIT;",
    ]
    return "\n".join(lines) + "\n"


def apply_via_client(crosswalk: dict[str, str]) -> None:
    """Apply the same backfill through supabase-py's rpc/upsert path.
    Uses per-school UPDATE rather than the CTE form because the PostgREST
    client doesn't accept raw SQL. Slower but simpler.

    Operators should prefer --emit-sql for the real production run
    (~2,400 round-trips over HTTPS takes several minutes and is
    network-fragile). This path exists for dev-loop convenience and
    small-scope backfills."""
    from dotenv import load_dotenv
    from supabase import create_client

    load_dotenv(REPO_ROOT / ".env")
    url = os.environ["SUPABASE_URL"]
    key = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
    sb = create_client(url, key)

    # Preflight: fail loudly if the ipeds_id column doesn't exist yet.
    # Without this check, every per-school UPDATE silently 400s and the
    # script reports "Updated 0 rows" with no indication that the
    # migration hasn't landed.
    try:
        sb.table("cds_documents").select("ipeds_id").limit(1).execute()
    except Exception as e:
        raise SystemExit(
            "cds_documents.ipeds_id column not found — apply migration "
            "20260420170000_ipeds_id.sql before running --apply. "
            f"(underlying error: {e})"
        )

    updated_rows = 0
    schools_touched = 0
    schools_no_match = 0
    for sid, ipeds in sorted(crosswalk.items()):
        # is_("ipeds_id", "null") ensures we don't overwrite values the
        # edge function may have already written. Idempotent.
        res = (
            sb.table("cds_documents")
            .update({"ipeds_id": ipeds})
            .eq("school_id", sid)
            .is_("ipeds_id", "null")
            .execute()
        )
        rows = len(res.data or [])
        if rows:
            updated_rows += rows
            schools_touched += 1
        else:
            # Could mean "no cds_documents rows for this school yet" OR
            # "all rows already have ipeds_id." Both are fine outcomes;
            # we just can't distinguish them without an extra query.
            schools_no_match += 1
    print(
        f"Updated {updated_rows} cds_documents rows across "
        f"{schools_touched}/{len(crosswalk)} schools. "
        f"{schools_no_match} schools had no rows matching ipeds_id IS NULL "
        "(already backfilled or no archives yet).",
        file=sys.stderr,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Write via supabase-py service-role client")
    parser.add_argument("--emit-sql", action="store_true", help="Emit SQL to stdout (default)")
    args = parser.parse_args()

    crosswalk = load_crosswalk()
    if not crosswalk:
        print("No IPEDS crosswalk entries found in schools.yaml", file=sys.stderr)
        return 1

    if args.apply:
        apply_via_client(crosswalk)
    else:
        sql = generate_sql(crosswalk)
        # Self-check: confirm every crosswalk entry made it into the SQL.
        # Catches generator regressions (escape bugs, missing commas, etc.)
        # before the SQL reaches an operator's editor.
        emitted = sql.count("\n    (")
        if emitted != len(crosswalk):
            raise SystemExit(
                f"generator drift: {emitted} VALUES rows emitted, "
                f"{len(crosswalk)} crosswalk entries. Aborting."
            )
        print(sql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
